//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PullRequestHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5eda3f519cb0ab43f1f5febcf5d382e96f411cf1")]
        public string GitHubToken {
            get {
                return ((string)(this["GitHubToken"]));
            }
            set {
                this["GitHubToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RobRobertsCE")]
        public string GitHubUserName {
            get {
                return ((string)(this["GitHubUserName"]));
            }
            set {
                this["GitHubUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CenterEdge")]
        public string GitHubRepoOwner {
            get {
                return ((string)(this["GitHubRepoOwner"]));
            }
            set {
                this["GitHubRepoOwner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://centeredge.atlassian.net")]
        public string JiraUrl {
            get {
                return ((string)(this["JiraUrl"]));
            }
            set {
                this["JiraUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rroberts")]
        public string JiraUserName {
            get {
                return ((string)(this["JiraUserName"]));
            }
            set {
                this["JiraUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hel-j205")]
        public string JiraUserPassword {
            get {
                return ((string)(this["JiraUserPassword"]));
            }
            set {
                this["JiraUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rroberts")]
        public string TeamCityUserName {
            get {
                return ((string)(this["TeamCityUserName"]));
            }
            set {
                this["TeamCityUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hel-j205")]
        public string TeamCityPassword {
            get {
                return ((string)(this["TeamCityPassword"]));
            }
            set {
                this["TeamCityPassword"] = value;
            }
        }
    }
}
